#!/usr/bin/env python3
"""Generate the data-independent and early handoff files (Agnibha -> Abhinav). Run after prepare_data.py.

Writes:
    handoff/hann_1024.h, handoff/hann_1024.npy         Hann window of features_spec.md (symmetric, N = 1024)
    firmware/bench/stored_inputs.cpp                    the 5 windows behind INPUT 0..4 (generated, never hand-edited)
    handoff/test_vectors/stored_inputs.npy / .json      the same 5 windows + their provenance, for host-side checks

The 5 stored windows are drawn from the P2 fold-0 TEST set (load 0 HP, non-overlapping windows). That is the deployed
instance's test data, so no stored window was ever seen in training. One window per class listed in STORED_CLASSES,
taken from the middle of the recording.

Usage:
    python ml/export_handoff.py            # uses data/processed/{windows.npy, manifest.parquet}
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1]
WIN = 1024
# N, IR007, OR007, B014, IR021: normal + all three fault types + all three sizes.
STORED_CLASSES = [0, 1, 3, 5, 7]
STORED_LOAD_HP = 0          # P2 fold 0 holds out load 0 -> these windows are test data for the deployed models


def hann_symmetric(n: int = WIN) -> np.ndarray:
    """w[n] = 0.5 - 0.5 cos(2 pi n / (N - 1)), n = 0..N-1 (features_spec.md, R2/R3)."""
    k = np.arange(n, dtype=np.float64)
    return (0.5 - 0.5 * np.cos(2.0 * np.pi * k / (n - 1))).astype(np.float32)


def c_floats(a: np.ndarray, per_line: int = 6, indent: str = "    ") -> str:
    """float32 array -> C initializer text that round-trips exactly (9 significant digits, always has an exponent)."""
    vals = [f"{float(v):.9e}f" for v in np.asarray(a, dtype=np.float32).ravel()]
    lines = [indent + ", ".join(vals[i:i + per_line]) + "," for i in range(0, len(vals), per_line)]
    return "\n".join(lines)


def write_hann(out_dir: Path) -> None:
    w = hann_symmetric()
    np.save(out_dir / "hann_1024.npy", w)
    (out_dir / "hann_1024.h").write_text(
        "// hann_1024.h - GENERATED by ml/export_handoff.py; do not edit.\n"
        "// Symmetric Hann window, w[n] = 0.5 - 0.5*cos(2*pi*n/1023), n = 0..1023 (handoff/features_spec.md).\n"
        "#pragma once\n\n"
        "static const float g_hann_1024[1024] = {\n" + c_floats(w) + "\n};\n")


def pick_stored(manifest: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for c in STORED_CLASSES:
        cand = manifest[(manifest.class10 == c) & (manifest.load_hp == STORED_LOAD_HP)
                        & (manifest.start_idx % WIN == 0)].sort_values("start_idx")
        if cand.empty:
            raise SystemExit(f"no non-overlapping load-{STORED_LOAD_HP} window for class {c}")
        rows.append(cand.iloc[len(cand) // 2])
    return pd.DataFrame(rows).reset_index(drop=True)


def write_stored(windows: np.ndarray, manifest: pd.DataFrame, cpp: Path, tv_dir: Path) -> None:
    names = {c["id"]: c["name"] for c in json.loads((REPO / "handoff" / "classes.json").read_text())["class10"]}
    sel = pick_stored(manifest)
    X = windows[sel.window_id.to_numpy()].astype(np.float32)
    assert X.shape == (5, WIN)

    tv_dir.mkdir(parents=True, exist_ok=True)
    np.save(tv_dir / "stored_inputs.npy", X)
    meta = [{"j": j, "window_id": int(r.window_id), "file_id": int(r.file_id), "class10": int(r.class10),
             "name": names[int(r.class10)], "load_hp": int(r.load_hp), "start_idx": int(r.start_idx)}
            for j, r in enumerate(sel.itertuples(index=False))]
    (tv_dir / "stored_inputs.json").write_text(json.dumps(
        {"source": "P2 fold 0 test set (load 0 HP), non-overlapping windows, middle of each recording",
         "inputs": meta}, indent=2) + "\n")

    body = []
    for j, m in enumerate(meta):
        body.append(f"  // INPUT {j}: {m['name']} (class10={m['class10']}), CWRU file {m['file_id']}, "
                    f"load {m['load_hp']} HP, start_idx {m['start_idx']}, window_id {m['window_id']}\n"
                    "  {\n" + c_floats(X[j]) + "\n  },")
    cpp.write_text(
        "// stored_inputs.cpp - GENERATED by ml/export_handoff.py; do not edit.\n"
        "// The 5 fixed test windows behind INPUT 0..4 (12 kHz, raw accelerometer units, common 5 kHz low-pass),\n"
        "// from the P2 fold-0 test set. Provenance: handoff/test_vectors/stored_inputs.json.\n"
        "// `const` keeps the 20 KB array in flash (.rodata).\n"
        '#include "stored_inputs.h"\n\n'
        "const float g_stored_inputs[BENCH_N_INPUTS][BENCH_WIN] = {\n" + "\n".join(body) + "\n};\n")
    for m in meta:
        print(f"  INPUT {m['j']}: {m['name']:<6} file {m['file_id']}  window_id {m['window_id']}")


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--processed", type=Path, default=REPO / "data" / "processed")
    p.add_argument("--handoff", type=Path, default=REPO / "handoff")
    p.add_argument("--stored-cpp", type=Path, default=REPO / "firmware" / "bench" / "stored_inputs.cpp")
    a = p.parse_args()

    a.handoff.mkdir(parents=True, exist_ok=True)
    write_hann(a.handoff)
    print(f"wrote {a.handoff / 'hann_1024.h'}")
    W = np.load(a.processed / "windows.npy", mmap_mode="r")
    M = pd.read_parquet(a.processed / "manifest.parquet")
    write_stored(W, M, a.stored_cpp, a.handoff / "test_vectors")
    print(f"wrote {a.stored_cpp} and {a.handoff / 'test_vectors'}/stored_inputs.*")


if __name__ == "__main__":
    main()
